FROM pytorch/pytorch:latest

RUN pip install torch==1.2.0
RUN pip install pytorch-transformers==1.2.0
RUN pip install pandas
RUN pip install imbalanced-learn
RUN pip install tensorboardX
RUN pip install records==0.5.2
RUN pip install babel
RUN pip install matplotlib
RUN pip install defusedxml
RUN pip install tqdm




ENV PYTHONPATH /workspace

WORKDIR /workspace